//! Exact application schema and parent-first transfer order.

use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Kind {
    Integer,
    Boolean,
    Text,
    Json,
    Timestamp,
    Date,
}

#[derive(Debug)]
pub struct Table {
    pub name: &'static str,
    pub columns: &'static [(&'static str, Kind)],
    pub keys: &'static [&'static str],
}

pub static TABLES: &[Table] = &[
    Table {
        name: "monitors",
        columns: &[
            ("id", Kind::Integer),
            ("key", Kind::Text),
            ("name", Kind::Text),
            ("check", Kind::Json),
            ("interval_ms", Kind::Integer),
            ("retry_interval_ms", Kind::Integer),
            ("timeout_ms", Kind::Integer),
            ("retries", Kind::Integer),
            ("invert", Kind::Boolean),
            ("degraded_after_ms", Kind::Integer),
            ("resend_every", Kind::Integer),
            ("active", Kind::Boolean),
            ("tags", Kind::Text),
            ("group_path", Kind::Text),
            ("created_at", Kind::Timestamp),
            ("updated_at", Kind::Timestamp),
        ],
        keys: &["id"],
    },
    Table {
        name: "admin_users",
        columns: &[
            ("id", Kind::Integer),
            ("github_id", Kind::Integer),
            ("login", Kind::Text),
            ("name", Kind::Text),
            ("avatar_url", Kind::Text),
            ("created_at", Kind::Timestamp),
            ("last_login_at", Kind::Timestamp),
        ],
        keys: &["id"],
    },
    Table {
        name: "status_pages",
        columns: &[
            ("id", Kind::Integer),
            ("slug", Kind::Text),
            ("title", Kind::Text),
            ("description", Kind::Text),
            ("accent", Kind::Text),
            ("theme", Kind::Text),
            ("look", Kind::Text),
            ("published", Kind::Boolean),
            ("website_url", Kind::Text),
            ("website_label", Kind::Text),
            ("logo", Kind::Text),
            ("favicon", Kind::Text),
            ("created_at", Kind::Timestamp),
            ("updated_at", Kind::Timestamp),
        ],
        keys: &["id"],
    },
    Table {
        name: "notification_channels",
        columns: &[
            ("id", Kind::Integer),
            ("name", Kind::Text),
            ("kind", Kind::Text),
            ("url", Kind::Text),
            ("secret", Kind::Text),
            ("default_on", Kind::Boolean),
            ("routing", Kind::Json),
            ("created_at", Kind::Timestamp),
        ],
        keys: &["id"],
    },
    Table {
        name: "maintenances",
        columns: &[
            ("id", Kind::Integer),
            ("title", Kind::Text),
            ("description", Kind::Text),
            ("starts_at", Kind::Timestamp),
            ("ends_at", Kind::Timestamp),
            ("repeat", Kind::Text),
            ("repeat_until", Kind::Timestamp),
            ("created_at", Kind::Timestamp),
        ],
        keys: &["id"],
    },
    Table {
        name: "incidents",
        columns: &[
            ("id", Kind::Integer),
            ("title", Kind::Text),
            ("impact", Kind::Text),
            ("status", Kind::Text),
            ("kind", Kind::Text),
            ("monitor_id", Kind::Integer),
            ("started_at", Kind::Timestamp),
            ("resolved_at", Kind::Timestamp),
        ],
        keys: &["id"],
    },
    Table {
        name: "monitor_runtime",
        columns: &[
            ("monitor_id", Kind::Integer),
            ("state", Kind::Text),
            ("consecutive_failures", Kind::Integer),
            ("next_run_at", Kind::Timestamp),
            ("scheduled_for", Kind::Timestamp),
            ("claimed_by", Kind::Text),
            ("last_checked_at", Kind::Timestamp),
            ("last_latency_ms", Kind::Integer),
            ("last_status_code", Kind::Integer),
            ("last_error", Kind::Text),
            ("state_changed_at", Kind::Timestamp),
            ("last_push_at", Kind::Timestamp),
            ("last_push_up", Kind::Boolean),
            ("last_push_message", Kind::Text),
            ("last_push_ms", Kind::Integer),
            ("cert_expires_at", Kind::Timestamp),
            ("cert_warned_days", Kind::Integer),
        ],
        keys: &["monitor_id"],
    },
    Table {
        name: "check_results",
        columns: &[
            ("id", Kind::Integer),
            ("monitor_id", Kind::Integer),
            ("scheduled_for", Kind::Timestamp),
            ("checked_at", Kind::Timestamp),
            ("health", Kind::Text),
            ("state_after", Kind::Text),
            ("latency_ms", Kind::Integer),
            ("status_code", Kind::Integer),
            ("error_kind", Kind::Text),
            ("error", Kind::Text),
            ("region", Kind::Text),
        ],
        keys: &["id"],
    },
    Table {
        name: "monitor_daily",
        columns: &[
            ("monitor_id", Kind::Integer),
            ("day", Kind::Date),
            ("total", Kind::Integer),
            ("up", Kind::Integer),
            ("degraded", Kind::Integer),
            ("pending", Kind::Integer),
            ("down", Kind::Integer),
            ("maintenance", Kind::Integer),
            ("latency_sum_ms", Kind::Integer),
            ("latency_count", Kind::Integer),
            ("latency_max_ms", Kind::Integer),
        ],
        keys: &["monitor_id", "day"],
    },
    Table {
        name: "page_sections",
        columns: &[
            ("id", Kind::Integer),
            ("page_id", Kind::Integer),
            ("name", Kind::Text),
            ("position", Kind::Integer),
        ],
        keys: &["id"],
    },
    Table {
        name: "page_components",
        columns: &[
            ("id", Kind::Integer),
            ("section_id", Kind::Integer),
            ("monitor_id", Kind::Integer),
            ("label", Kind::Text),
            ("position", Kind::Integer),
        ],
        keys: &["id"],
    },
    Table {
        name: "custom_domains",
        columns: &[
            ("id", Kind::Integer),
            ("page_id", Kind::Integer),
            ("hostname", Kind::Text),
            ("status", Kind::Text),
            ("last_error", Kind::Text),
            ("verified_at", Kind::Timestamp),
            ("cert_ok_at", Kind::Timestamp),
            ("last_checked_at", Kind::Timestamp),
            ("created_at", Kind::Timestamp),
        ],
        keys: &["id"],
    },
    Table {
        name: "monitor_channels",
        columns: &[("monitor_id", Kind::Integer), ("channel_id", Kind::Integer)],
        keys: &["monitor_id", "channel_id"],
    },
    Table {
        name: "notification_outbox",
        columns: &[
            ("id", Kind::Integer),
            ("channel_id", Kind::Integer),
            ("monitor_id", Kind::Integer),
            ("event", Kind::Text),
            ("payload", Kind::Json),
            ("attempts", Kind::Integer),
            ("next_attempt_at", Kind::Timestamp),
            ("created_at", Kind::Timestamp),
            ("sent_at", Kind::Timestamp),
            ("failed_at", Kind::Timestamp),
            ("last_error", Kind::Text),
        ],
        keys: &["id"],
    },
    Table {
        name: "maintenance_monitors",
        columns: &[
            ("maintenance_id", Kind::Integer),
            ("monitor_id", Kind::Integer),
        ],
        keys: &["maintenance_id", "monitor_id"],
    },
    Table {
        name: "incident_updates",
        columns: &[
            ("id", Kind::Integer),
            ("incident_id", Kind::Integer),
            ("status", Kind::Text),
            ("body", Kind::Text),
            ("created_at", Kind::Timestamp),
        ],
        keys: &["id"],
    },
    Table {
        name: "incident_monitors",
        columns: &[
            ("incident_id", Kind::Integer),
            ("monitor_id", Kind::Integer),
        ],
        keys: &["incident_id", "monitor_id"],
    },
    Table {
        name: "sessions",
        columns: &[
            ("token_hash", Kind::Text),
            ("user_id", Kind::Integer),
            ("created_at", Kind::Timestamp),
            ("expires_at", Kind::Timestamp),
            ("last_seen_at", Kind::Timestamp),
            ("user_agent", Kind::Text),
        ],
        keys: &["token_hash"],
    },
    Table {
        name: "api_tokens",
        columns: &[
            ("id", Kind::Integer),
            ("name", Kind::Text),
            ("token_hash", Kind::Text),
            ("scope", Kind::Text),
            ("created_by", Kind::Text),
            ("created_at", Kind::Timestamp),
            ("last_used_at", Kind::Timestamp),
        ],
        keys: &["id"],
    },
];
