CREATE TABLE "monitor_daily" (
    "monitor_id" BIGINT NOT NULL,
    "day" DATE NOT NULL,
    "total" BIGINT NOT NULL,
    "up" BIGINT NOT NULL,
    "degraded" BIGINT NOT NULL,
    "pending" BIGINT NOT NULL,
    "down" BIGINT NOT NULL,
    "maintenance" BIGINT NOT NULL,
    "latency_sum_ms" BIGINT NOT NULL,
    "latency_count" BIGINT NOT NULL,
    "latency_max_ms" BIGINT NOT NULL,
    PRIMARY KEY ("monitor_id", "day")
);
CREATE TABLE "monitor_runtime" (
    "monitor_id" BIGINT NOT NULL,
    "state" TEXT NOT NULL,
    "consecutive_failures" INTEGER NOT NULL,
    "next_run_at" TIMESTAMPTZ(6) NOT NULL,
    "scheduled_for" TIMESTAMPTZ(6),
    "claimed_by" TEXT,
    "last_checked_at" TIMESTAMPTZ(6),
    "last_latency_ms" BIGINT,
    "last_status_code" INTEGER,
    "last_error" TEXT,
    "state_changed_at" TIMESTAMPTZ(6),
    PRIMARY KEY ("monitor_id")
);
CREATE INDEX "index_monitor_runtime_by_next_run_at" ON "monitor_runtime" ("next_run_at");
CREATE TABLE "check_results" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "monitor_id" BIGINT NOT NULL,
    "scheduled_for" TIMESTAMPTZ(6) NOT NULL,
    "checked_at" TIMESTAMPTZ(6) NOT NULL,
    "health" TEXT NOT NULL,
    "state_after" TEXT NOT NULL,
    "latency_ms" BIGINT,
    "status_code" INTEGER,
    "error_kind" TEXT,
    "error" TEXT,
    "region" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_check_results_by_checked_at" ON "check_results" ("checked_at");
CREATE TABLE "monitors" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "check" JSONB NOT NULL,
    "interval_ms" BIGINT NOT NULL,
    "retry_interval_ms" BIGINT NOT NULL,
    "timeout_ms" BIGINT NOT NULL,
    "retries" INTEGER NOT NULL,
    "invert" BOOLEAN NOT NULL,
    "degraded_after_ms" BIGINT,
    "resend_every" INTEGER NOT NULL,
    "active" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_monitors_by_key" ON "monitors" ("key");
