CREATE TABLE "sessions" (
    "token_hash" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "last_seen_at" TIMESTAMPTZ(6) NOT NULL,
    "user_agent" TEXT,
    PRIMARY KEY ("token_hash")
);
CREATE INDEX "index_sessions_by_user_id" ON "sessions" ("user_id");
CREATE INDEX "index_sessions_by_expires_at" ON "sessions" ("expires_at");
CREATE TABLE "admin_users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "github_id" BIGINT NOT NULL,
    "login" TEXT NOT NULL,
    "name" TEXT,
    "avatar_url" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "last_login_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_admin_users_by_github_id" ON "admin_users" ("github_id");
CREATE UNIQUE INDEX "index_admin_users_by_login" ON "admin_users" ("login");
