CREATE TABLE "page_sections" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "page_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_page_sections_by_page_id" ON "page_sections" ("page_id");
CREATE TABLE "page_components" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "section_id" BIGINT NOT NULL,
    "monitor_id" BIGINT NOT NULL,
    "label" TEXT,
    "position" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_page_components_by_section_id" ON "page_components" ("section_id");
CREATE INDEX "index_page_components_by_monitor_id" ON "page_components" ("monitor_id");
CREATE TABLE "status_pages" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "accent" TEXT,
    "theme" TEXT NOT NULL,
    "published" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_status_pages_by_slug" ON "status_pages" ("slug");
