CREATE TABLE "custom_domains" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "page_id" BIGINT NOT NULL,
    "hostname" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "last_error" TEXT,
    "verified_at" TIMESTAMPTZ(6),
    "cert_ok_at" TIMESTAMPTZ(6),
    "last_checked_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_custom_domains_by_page_id" ON "custom_domains" ("page_id");
CREATE UNIQUE INDEX "index_custom_domains_by_hostname" ON "custom_domains" ("hostname");
