CREATE TABLE "notification_outbox" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "channel_id" BIGINT NOT NULL,
    "monitor_id" BIGINT,
    "event" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "attempts" INTEGER NOT NULL,
    "next_attempt_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "sent_at" TIMESTAMPTZ(6),
    "failed_at" TIMESTAMPTZ(6),
    "last_error" TEXT,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_notification_outbox_by_channel_id" ON "notification_outbox" ("channel_id");
CREATE INDEX "index_notification_outbox_by_next_attempt_at" ON "notification_outbox" ("next_attempt_at");
CREATE TABLE "monitor_channels" (
    "monitor_id" BIGINT NOT NULL,
    "channel_id" BIGINT NOT NULL,
    PRIMARY KEY ("monitor_id", "channel_id")
);
CREATE INDEX "index_monitor_channels_by_channel_id" ON "monitor_channels" ("channel_id");
CREATE TABLE "notification_channels" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "secret" TEXT,
    "default_on" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
