CREATE TABLE "maintenances" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "starts_at" TIMESTAMPTZ(6) NOT NULL,
    "ends_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_maintenances_by_starts_at" ON "maintenances" ("starts_at");
CREATE INDEX "index_maintenances_by_ends_at" ON "maintenances" ("ends_at");
CREATE TABLE "maintenance_monitors" (
    "maintenance_id" BIGINT NOT NULL,
    "monitor_id" BIGINT NOT NULL,
    PRIMARY KEY ("maintenance_id", "monitor_id")
);
CREATE INDEX "index_maintenance_monitors_by_monitor_id" ON "maintenance_monitors" ("monitor_id");
