CREATE TABLE "incident_updates" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "incident_id" BIGINT NOT NULL,
    "status" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_incident_updates_by_incident_id" ON "incident_updates" ("incident_id");
CREATE TABLE "incidents" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" TEXT NOT NULL,
    "impact" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "monitor_id" BIGINT,
    "started_at" TIMESTAMPTZ(6) NOT NULL,
    "resolved_at" TIMESTAMPTZ(6),
    PRIMARY KEY ("id")
);
CREATE INDEX "index_incidents_by_monitor_id" ON "incidents" ("monitor_id");
CREATE INDEX "index_incidents_by_started_at" ON "incidents" ("started_at");
CREATE TABLE "incident_monitors" (
    "incident_id" BIGINT NOT NULL,
    "monitor_id" BIGINT NOT NULL,
    PRIMARY KEY ("incident_id", "monitor_id")
);
CREATE INDEX "index_incident_monitors_by_monitor_id" ON "incident_monitors" ("monitor_id");
