CREATE TABLE "api_tokens" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "created_by" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "last_used_at" TIMESTAMPTZ(6),
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_api_tokens_by_token_hash" ON "api_tokens" ("token_hash");
